### ISSUE TITLE
这个项目为什么没更新呢？

### ISSUE THREAD

**Issue by danMe66** [GordonChen13/jianzhi-v2#11]
这个项目为什么没更新呢？还是有些bug的，我看您好久没在github上了.....

**Comment by GordonChen13** [comment]
工作比较忙，小修小补的就不想折腾了。有打算用go，微服务来重写一遍的，不过涉及的坑越挖越多，还没开始。这个项目写得比较粗糙，是边学边写的，拼凑了比较多的功能。我这个项目的代码没多大参考价值的（写得比较烂，刚学编程为了找工作写的）。这个项目比较重要的东西，我觉得是一种努力用自己的技术去实现心中想法，碰到问题不怕折腾的精神。哈哈，感谢你对这个项目的关注，共勉吧

**Comment by danMe66** [comment]
这个项目确实挺好的，我看你也在github上很少出现啊，大佬在哪个圈子混？？嘻嘻
