### ISSUE TITLE
管理员

### ISSUE THREAD

**Issue by Breadem** [GordonChen13/jianzhi-v2#2]
请问有用户权限管理吗？  怎么用管理员账号登录？

**Comment by GordonChen13** [comment]
管理后台暂时还没有，权限管理也没有。主要实现的是商家发布兼职-用户咨询-商家回复-用户申请-商家确认-用户商家互评的一个流程。有时间下个版本再加进去吧

**Comment by Breadem** [comment]
好的 ，谢谢
