### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ghost** [GordonChen13/jianzhi-v2#5]
很多地方，验证jwt的时候，可以用中间件来实现，太多  $user = JWTAuth::parseToken()->authenticate();这样的写法了。不过，前端还是挺不错的。

**Comment by GordonChen13** [comment]
嗯嗯，很好的一个建议哈。这是我第一个比较完整的项目，之前也没有跟人合作过。写代码的时候主要考虑的是功能实现。非常感谢你的建议哈
