### ISSUE TITLE
可以分享以下vue代码么，想学习下pusher的使用

### ISSUE THREAD

**Issue by dark-wind** [GordonChen13/jianzhi-v2#6]
只找到一个打包好的前端js包，想学习下pusher

**Comment by GordonChen13** [comment]
你看下/resources/assets/js/components/notifications目录，里面就是通知模块。
我用到了这个js库：https://github.com/happyDemon/vue-echo

**Comment by dark-wind** [comment]
恩恩，找到了，和平时看到的项目放的位置不太一样，非常感谢O(∩_∩)O
